#!/bin/sh

erreur () {
    echo ""
    echo "Utilisation : $0 fichier.deb"
    echo ""
    exit 1
}

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "\n$0 par Tex59dk - Aide :"
    erreur
fi

if [ "$1" = "" ]; then
    echo "\nErreur !"
    echo "fichier .deb requis !"
    erreur
fi

sucmd=""
if [ "$(id -u)" -ne "0" ]; then
    echo "\n\nAttention !\nIl se peut que rien n'apparaisse à l'écran quand un mot de passe est saisi...\n"
    sucmd="sudo"
fi

$sucmd dpkg -i $1
$sucmd apt install -f
echo "\nInstallation Terminée..."
