#!/bin/bash

if [ -f $1 ] ; then
  case $1 in
    *.tar.bz2)  tar xjf $1   ;;
    *.tar.gz)   tar xzf $1   ;;
    *.tar.xz)   tar zxvf $1  ;;
    *.bz2)      bunzip2 $1   ;;
    *.rar)      rar x $1     ;;
    *.gz)       gunzip $1    ;;
    *.tar)      tar xf $1    ;;
    *.tbz2)     tar xjf $1   ;;
    *.tgz)      tar xzf $1   ;;
    *.xz)       xz -d $1     ;;
    *.zip)      unzip $1     ;;
    *.Z)        uncompress $1;;
    *)          echo "Si '$1' est une archive compressée, son contenu ne peut pas être extrait par $0." ;;
  esac
else
  echo "'$1' n'est pas un fichier."
fi

if [ $? != 0 ]; then
    echo "L'extraction de '$1' a échoué."
    exit $?
fi

if [ -f $1 ]; then
  echo -n "Souhaitez-vous supprimer l'archive '$1' [On] ? > "
  read -n 1 ans
  echo ""
  ans=${ans^}
  if [ $ans == “O” ]; then
    rm $1
    if [ $? == 0 ]; then
      echo "'$1' supprimé"
    else
      echo “ERREUR : '$1' n\'a pas été supprimé”
    fi 
  fi
fi

