#! /bin/bash

help(){

    #echo "$appname"
    aidetxt="Utilisation du programe ${appname^^}.\n\
    \n\
    Ce programme permet d'importer en nombre les fichiers\n\
    de configuration .ovpn contenus dans le dossier spécifié.\n\
    Veuillez également indiquer le nom d'utilisateur et\n\
    le mot de passe associés au compte OpenVPN."

    #~ echo "$aidetxt"
    yad --title="AIDE ${appname^^}" \
        --window-icon=help-faq \
        --text="$aidetxt"
}
export -f help

verif(){
    utilisateur=$(echo $OUTPUT | awk 'BEGIN {FS="," } { print $1 }')
    motdepasse=$(echo $OUTPUT | awk 'BEGIN {FS="," } { print $2 }')
    chemin=$(echo $OUTPUT | awk 'BEGIN {FS="," } { print $3 }')
    echo "Utilisateur = $utilisateur"
    echo "Mot de Passe = $motdepasse"
    echo "Chemin .ovpn = $chemin"
    nbrefichiers=$(find $chemin -maxdepth 1 -type f -name "*.ovpn" | wc -l)
    if [ "$utilisateur" = "" ]; then
        yad --title="ERREUR !!!" \
            --window-icon=dialog-warning \
            --width=200 --height=90 \
            --text="Aucun nom d'utilisater !\nVeuillez en indiquer un." \
            --text-align=center
    elif [ "$motdepasse" = "" ]; then
        yad --title="ERREUR !!!" \
            --window-icon=dialog-warning \
            --text="Aucun mot de passe !\nVeuillez en indiquer un." \
            --text-align=center
    elif ((nbrefichiers == 0)); then
        yad --title="ERREUR !!!" \
            --window-icon=dialog-warning \
            --text="Aucun fichier '.ovpn' dans ce dossier !\nVeuillez en choisir un autre." \
            --text-align=center
    else

        #read -p 'Username: ' username
        #read -p 'Password: ' password
        chemin="$chemin/*.ovpn"
        for path in $chemin
        do
            name=$(basename "$path" ".ovpn")

            echo "$name => $path"
            #read -p "Press 'Enter' to continue..." pause

            #sudo nmcli --terse connection delete id "$name" > /dev/null
            #sudo nmcli --terse connection import type openvpn file "$path" > /dev/null
            #sudo nmcli connection modify "$name" vpn.persistent true
            #sudo nmcli connection modify "$name" vpn.user-name "$utilisateur"
            #sudo nmcli connection modify "$name" +vpn.data "password-flags = 0, username = $utilisateur"
            #sudo nmcli connection modify "$name" +vpn.secrets "password=$motdepasse"
        done
    fi
}
export -f verif

#aidetxt=$(cat <<EOF
#Fichier d'aide en cours d'écriture.
#EOF
#)
export appname=$(basename "$0")
#echo "$appname"
export OUTPUT=$(yad --title="Importation .ovpn" \
    --text="Utilisez ce formulaire pour importer\ndes fichiers .ovpn en masse" \
    --image="/usr/share/icons/gnome/48x48/devices/network-vpn.png" \
    --button=gtk-ok:"bash -c verif" \
    --button=gtk-help:"bash -c help" \
    --button=gtk-quit:0 \
    --form --separator="," \
    --field="Utilisateur :" \
    --field="Mot de Passe :":H \
    --field="Dossier :":MDIR
)
