#!/bin/bash
clear
echo -e "\n"
echo -e " _____  _  _       \033[7m _   _       _   \033[m"
echo -e "| ____|| || | __ _ \033[7m| \\ | | ___ | |_ \033[m"
echo -e "|  _|  | || |/ _\` |\033[7m|  \\| |/ _ \\| __|\033[m"
echo -e "| |___ | || | (_| |\033[7m| |\\  |  __/| |_ \033[m"
echo -e "|_____||_||_|\\__,_|\033[7m|_| \\_|\\___| \\__|\033[m"
echo -e "                   \033[7m                 \033[m"
echo -e "\n"
echo -e "Présente :\n"
echo -e "Le script qui lance BeEF et Metasploit."
echo -e "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*\n"

if [ "$(id -u)" -ne "0" ] ; then
   dpkg -l zenity > /dev/null 2>&1
   INSTALLED=$?
   if [ $INSTALLED == '0' ]; then
      zenity --error --title "Attention !!!" --width 500 --height 100 --text "Ce script doit être exécuter en tant qu'utilisateur Root (Administrateur)...\nVous pouvez utiliser la commande : sudo $0"
   else
      echo -e "Attention !!!\nCe script doit être exécuter en tant qu'utilisateur Root (Administrateur)...\nVous pouvez utiliser la commande : sudo $0"
   fi
   exit 1
fi

echo -e "Lancement de BeEF"
echo -e "-----------------\n"
BeEF-xss

echo -e "\n"
echo -e "Lancement de MetasPloit"
echo -e "-----------------------\n"
msfconsole -x "load msgrpc ServerHost=127.0.0.1 User=msf Pass=Pierre SSL=y"

choix=""

while [ "$choix" = "" ]; do
   printf "\nAppuyer sur une touche pour arrêter BeEF..."
   read -n 1 choix
   choix=${choix^}
   #echo -e "\n\nChoix : $choix\n\n"
done

echo -e "\n"
echo -e "Arrêt de BeEF"
echo -e "-------------\n"
BeEF-xss-stop

echo -e "\n"
echo -e "Fin du script"
echo -e "-------------\n"
